import { HeroConfig, Item, Stats } from '../types/game';

export const GAME_CONFIG = {
  MAP_WIDTH: 2400,
  MAP_HEIGHT: 2400,
  TICK_RATE: 60,
  MATCH_DURATION_TARGET_SEC: 600, // ~10 minutes
  STARTING_GOLD: 300,
  PASSIVE_GOLD_PER_SEC: 3.5,
  MINION_WAVE_INTERVAL_SEC: 28,
  FIRST_MINION_SPAWN_SEC: 5,
  JUNGLE_SPAWN_SEC: 15,
  LORD_SPAWN_SEC: 90,
  LORD_RESPAWN_SEC: 120,
  MAX_HERO_LEVEL: 15,
  BASE_RESPAWN_SEC: 6,
  RESPAWN_PER_LEVEL_SEC: 2.2,
  FOUNTAIN_HEAL_PER_SEC: 250,
  FOUNTAIN_MANA_PER_SEC: 120,
  EXP_TABLE: [
    0,     // Lv 1
    180,   // Lv 2
    420,   // Lv 3
    750,   // Lv 4 (Ult unlock!)
    1150,  // Lv 5
    1650,  // Lv 6
    2250,  // Lv 7
    2950,  // Lv 8
    3750,  // Lv 9
    4650,  // Lv 10
    5650,  // Lv 11
    6750,  // Lv 12
    7950,  // Lv 13
    9250,  // Lv 14
    10750  // Lv 15
  ],
  GOLD_REWARDS: {
    MINION_MELEE: 35,
    MINION_RANGED: 25,
    MINION_SIEGE: 60,
    LAST_HIT_BONUS_MULT: 1.4,
    HERO_KILL: 220,
    FIRST_BLOOD_BONUS: 100,
    HERO_ASSIST: 80,
    TOWER_KILL: 200,
    INHIBITOR_KILL: 250,
    LORD_KILL_TEAM: 300,
    RED_BUFF_GOLD: 70,
    BLUE_BUFF_GOLD: 70,
    SCUTTLER_GOLD: 55,
  },
  XP_REWARDS: {
    MINION_MELEE: 45,
    MINION_RANGED: 35,
    MINION_SIEGE: 80,
    HERO_KILL: 250,
    TOWER_KILL: 180,
    LORD_KILL: 500,
    RED_BUFF_XP: 120,
    BLUE_BUFF_XP: 120,
    SCUTTLER_XP: 80,
  },
};

export const HEROES_CONFIG: Record<string, HeroConfig> = {
  vanguard: {
    id: 'vanguard',
    name: 'Vanguard',
    title: 'The Iron Bastion',
    role: 'tank',
    avatarColor: '#3b82f6',
    primaryColor: '#2563eb',
    secondaryColor: '#93c5fd',
    lore: 'An unbreakable armored juggernaut forged in ancient steel, Vanguard controls the battlefield with towering shields and ground-shattering seismic force.',
    baseStats: {
      hp: 3100,
      maxHp: 3100,
      mana: 460,
      maxMana: 460,
      hpRegen: 12,
      manaRegen: 4,
      attack: 110,
      magicPower: 0,
      armor: 55,
      magicResist: 45,
      moveSpeed: 235,
      attackSpeed: 0.9,
      attackRange: 85,
      cooldownReduction: 0,
      critChance: 0,
      lifesteal: 0,
    },
    growthStats: {
      hp: 210,
      mana: 25,
      attack: 6.5,
      armor: 5.5,
      magicResist: 3.5,
    },
    passive: {
      name: 'Unyielding Resolve',
      description: 'When Vanguard drops below 35% HP, gains a shield equal to 18% max HP for 5s (60s cooldown).',
    },
    skills: [
      {
        id: 'vanguard_s1',
        name: 'Shield Charge',
        description: 'Charges forward, ramming enemies to deal physical damage and knocking them back.',
        cooldown: 8,
        currentCooldown: 0,
        manaCost: 50,
        range: 300,
        targetType: 'dash',
        damageType: 'physical',
        baseDamage: 160,
        damagePerLevel: 35,
        scalingAD: 0.6,
        scalingAP: 0,
        level: 1,
        maxLevel: 4,
        icon: '🛡️',
        color: '#60a5fa',
      },
      {
        id: 'vanguard_s2',
        name: 'Earth Tremor',
        description: 'Slams his tower shield into the ground, dealing damage and slowing surrounding enemies by 50% for 2s.',
        cooldown: 9,
        currentCooldown: 0,
        manaCost: 60,
        range: 0,
        radius: 220,
        targetType: 'aoe_circle',
        damageType: 'physical',
        baseDamage: 140,
        damagePerLevel: 40,
        scalingAD: 0.5,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '🔨',
        color: '#3b82f6',
      },
      {
        id: 'vanguard_s3',
        name: 'Fortress Aegis',
        description: 'Hardens his defense, gaining +40 armor and magic resist and regenerating 8% max HP over 4s.',
        cooldown: 12,
        currentCooldown: 0,
        manaCost: 65,
        range: 0,
        targetType: 'self',
        damageType: 'physical',
        baseDamage: 0,
        damagePerLevel: 0,
        scalingAD: 0,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '✨',
        color: '#93c5fd',
      },
      {
        id: 'vanguard_ult',
        name: 'Titan Drop',
        description: 'Leaps into the air and crashes into the target location, dealing heavy damage and stunning all enemies in the epicenter for 1.5s.',
        cooldown: 35,
        currentCooldown: 0,
        manaCost: 110,
        range: 480,
        radius: 260,
        targetType: 'aoe_circle',
        damageType: 'physical',
        baseDamage: 380,
        damagePerLevel: 90,
        scalingAD: 0.9,
        scalingAP: 0,
        level: 0,
        maxLevel: 3,
        icon: '💥',
        color: '#1d4ed8',
      },
    ],
  },

  kaelen: {
    id: 'kaelen',
    name: 'Kaelen',
    title: 'The Blade Warden',
    role: 'fighter',
    avatarColor: '#f97316',
    primaryColor: '#ea580c',
    secondaryColor: '#fdba74',
    lore: 'A martial virtuoso wielding dual sun-forged greatswords, Kaelen excels in sustained melee duels and aggressive skirmishes.',
    baseStats: {
      hp: 2750,
      maxHp: 2750,
      mana: 420,
      maxMana: 420,
      hpRegen: 10,
      manaRegen: 4,
      attack: 135,
      magicPower: 0,
      armor: 42,
      magicResist: 36,
      moveSpeed: 245,
      attackSpeed: 1.05,
      attackRange: 90,
      cooldownReduction: 0,
      critChance: 0.05,
      lifesteal: 0.05,
    },
    growthStats: {
      hp: 175,
      mana: 20,
      attack: 8.5,
      armor: 4.2,
      magicResist: 2.8,
    },
    passive: {
      name: 'Sunblade Vigor',
      description: 'Basic attacks restore 4% missing HP and grant 6% bonus attack speed (stacks up to 5 times).',
    },
    skills: [
      {
        id: 'kaelen_s1',
        name: 'Blade Rush',
        description: 'Dashes forward slicing all targets in his path. Can be recast within 3s if it hits an enemy.',
        cooldown: 7,
        currentCooldown: 0,
        manaCost: 45,
        range: 320,
        targetType: 'dash',
        damageType: 'physical',
        baseDamage: 180,
        damagePerLevel: 45,
        scalingAD: 0.8,
        scalingAP: 0,
        level: 1,
        maxLevel: 4,
        icon: '⚔️',
        color: '#fb923c',
      },
      {
        id: 'kaelen_s2',
        name: 'Whirlwind Slash',
        description: 'Spins with dual blades, hitting all nearby enemies twice and slowing them by 35%.',
        cooldown: 8,
        currentCooldown: 0,
        manaCost: 55,
        range: 0,
        radius: 200,
        targetType: 'aoe_circle',
        damageType: 'physical',
        baseDamage: 210,
        damagePerLevel: 50,
        scalingAD: 0.85,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '🌀',
        color: '#f97316',
      },
      {
        id: 'kaelen_s3',
        name: 'Battle Cry',
        description: 'Roars with battle passion, breaking slows, gaining 30% movement speed and a 200 HP shield for 3s.',
        cooldown: 11,
        currentCooldown: 0,
        manaCost: 50,
        range: 0,
        targetType: 'self',
        damageType: 'physical',
        baseDamage: 0,
        damagePerLevel: 0,
        scalingAD: 0,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '🦁',
        color: '#fed7aa',
      },
      {
        id: 'kaelen_ult',
        name: 'Solar Guillotine',
        description: 'Jumps toward an enemy hero, smashing down with devastating force dealing physical damage plus missing HP execution damage.',
        cooldown: 32,
        currentCooldown: 0,
        manaCost: 90,
        range: 380,
        targetType: 'target_unit',
        damageType: 'physical',
        baseDamage: 450,
        damagePerLevel: 120,
        scalingAD: 1.25,
        scalingAP: 0,
        level: 0,
        maxLevel: 3,
        icon: '⚡',
        color: '#c2410c',
      },
    ],
  },

  pyra: {
    id: 'pyra',
    name: 'Pyra',
    title: 'The Flame Weaver',
    role: 'mage',
    avatarColor: '#ef4444',
    primaryColor: '#dc2626',
    secondaryColor: '#fca5a5',
    lore: 'Master of elemental hellfire, Pyra incinerates enemy battle lines from long range with catastrophic burst pyromancy.',
    baseStats: {
      hp: 2300,
      maxHp: 2300,
      mana: 580,
      maxMana: 580,
      hpRegen: 7,
      manaRegen: 6.5,
      attack: 85,
      magicPower: 45,
      armor: 28,
      magicResist: 28,
      moveSpeed: 235,
      attackSpeed: 0.85,
      attackRange: 270,
      cooldownReduction: 0.05,
      critChance: 0,
      lifesteal: 0,
    },
    growthStats: {
      hp: 140,
      mana: 35,
      attack: 4.5,
      armor: 3.2,
      magicResist: 2.5,
    },
    passive: {
      name: 'Ignition Brand',
      description: 'Skills apply Burn dealing 3% of enemy current HP as magic damage over 3 seconds.',
    },
    skills: [
      {
        id: 'pyra_s1',
        name: 'Pyrobomb',
        description: 'Launches a blazing orb in a straight line that explodes upon reaching the target or hitting an enemy.',
        cooldown: 5.5,
        currentCooldown: 0,
        manaCost: 60,
        range: 480,
        radius: 120,
        targetType: 'skillshot_line',
        damageType: 'magical',
        baseDamage: 240,
        damagePerLevel: 55,
        scalingAD: 0,
        scalingAP: 0.85,
        level: 1,
        maxLevel: 4,
        icon: '🔥',
        color: '#ef4444',
      },
      {
        id: 'pyra_s2',
        name: 'Flame Pillar',
        description: 'Summons a pillar of fire after a 0.5s delay, knocking up and stunning enemies for 1.2s.',
        cooldown: 9,
        currentCooldown: 0,
        manaCost: 75,
        range: 420,
        radius: 150,
        targetType: 'aoe_circle',
        damageType: 'magical',
        baseDamage: 220,
        damagePerLevel: 50,
        scalingAD: 0,
        scalingAP: 0.75,
        level: 0,
        maxLevel: 4,
        icon: '🌋',
        color: '#b91c1c',
      },
      {
        id: 'pyra_s3',
        name: 'Blazing Blink',
        description: 'Flashes a short distance leaving a trail of fire that damages enemies who walk across it.',
        cooldown: 11,
        currentCooldown: 0,
        manaCost: 65,
        range: 300,
        targetType: 'dash',
        damageType: 'magical',
        baseDamage: 120,
        damagePerLevel: 30,
        scalingAD: 0,
        scalingAP: 0.4,
        level: 0,
        maxLevel: 4,
        icon: '✨',
        color: '#f87171',
      },
      {
        id: 'pyra_ult',
        name: 'Meteor Cataclysm',
        description: 'Calls down a colossal meteor shower on a target area, blasting enemies with huge burst magic damage.',
        cooldown: 38,
        currentCooldown: 0,
        manaCost: 130,
        range: 520,
        radius: 280,
        targetType: 'aoe_circle',
        damageType: 'magical',
        baseDamage: 620,
        damagePerLevel: 140,
        scalingAD: 0,
        scalingAP: 1.4,
        level: 0,
        maxLevel: 3,
        icon: '☄️',
        color: '#7f1d1d',
      },
    ],
  },

  lyra: {
    id: 'lyra',
    name: 'Lyra',
    title: 'The Dawn Sniper',
    role: 'marksman',
    avatarColor: '#eab308',
    primaryColor: '#ca8a04',
    secondaryColor: '#fde047',
    lore: 'Armed with a light-energy compound bow, Lyra eliminates foes with lethal pinpoint precision from extreme range.',
    baseStats: {
      hp: 2250,
      maxHp: 2250,
      mana: 400,
      maxMana: 400,
      hpRegen: 7,
      manaRegen: 3.5,
      attack: 130,
      magicPower: 0,
      armor: 26,
      magicResist: 26,
      moveSpeed: 240,
      attackSpeed: 1.15,
      attackRange: 290,
      cooldownReduction: 0,
      critChance: 0.1,
      lifesteal: 0,
    },
    growthStats: {
      hp: 145,
      mana: 22,
      attack: 9.5,
      armor: 3.0,
      magicResist: 2.2,
    },
    passive: {
      name: 'Eagle Eye',
      description: 'Every 3rd basic attack pierces armor and deals 30% bonus critical physical damage.',
    },
    skills: [
      {
        id: 'lyra_s1',
        name: 'Piercing Arrow',
        description: 'Fires a high-velocity solar arrow that pierces through all enemies in a line, dealing damage.',
        cooldown: 6,
        currentCooldown: 0,
        manaCost: 45,
        range: 550,
        targetType: 'skillshot_line',
        damageType: 'physical',
        baseDamage: 220,
        damagePerLevel: 55,
        scalingAD: 0.95,
        scalingAP: 0,
        level: 1,
        maxLevel: 4,
        icon: '🏹',
        color: '#eab308',
      },
      {
        id: 'lyra_s2',
        name: 'Solar Volley',
        description: 'Fires a fan of 5 arrows forward, dealing damage and slowing enemies struck by 40% for 2s.',
        cooldown: 8,
        currentCooldown: 0,
        manaCost: 55,
        range: 420,
        targetType: 'cone',
        damageType: 'physical',
        baseDamage: 190,
        damagePerLevel: 45,
        scalingAD: 0.75,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '✨',
        color: '#facc15',
      },
      {
        id: 'lyra_s3',
        name: 'Acrobatic Vault',
        description: 'Tumbles backward while firing a tracking shot at the nearest enemy hero and gaining 25% attack speed.',
        cooldown: 9,
        currentCooldown: 0,
        manaCost: 50,
        range: 280,
        targetType: 'dash',
        damageType: 'physical',
        baseDamage: 120,
        damagePerLevel: 30,
        scalingAD: 0.5,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '🤸',
        color: '#fef08a',
      },
      {
        id: 'lyra_ult',
        name: 'Dawn Cannon',
        description: 'Charges and fires an apocalyptic light beam spanning immense range, dealing massive damage to all enemies caught.',
        cooldown: 34,
        currentCooldown: 0,
        manaCost: 100,
        range: 900,
        targetType: 'skillshot_line',
        damageType: 'physical',
        baseDamage: 550,
        damagePerLevel: 130,
        scalingAD: 1.35,
        scalingAP: 0,
        level: 0,
        maxLevel: 3,
        icon: '☀️',
        color: '#a16207',
      },
    ],
  },

  zephyr: {
    id: 'zephyr',
    name: 'Zephyr',
    title: 'The Shadow Stalker',
    role: 'assassin',
    avatarColor: '#a855f7',
    primaryColor: '#9333ea',
    secondaryColor: '#d8b4fe',
    lore: 'A silent phantom cloaked in night, Zephyr slips past frontline defenses to execute priority targets in the blink of an eye.',
    baseStats: {
      hp: 2400,
      maxHp: 2400,
      mana: 450,
      maxMana: 450,
      hpRegen: 8,
      manaRegen: 4,
      attack: 142,
      magicPower: 0,
      armor: 32,
      magicResist: 30,
      moveSpeed: 260,
      attackSpeed: 1.1,
      attackRange: 85,
      cooldownReduction: 0.05,
      critChance: 0.1,
      lifesteal: 0,
    },
    growthStats: {
      hp: 155,
      mana: 24,
      attack: 9.8,
      armor: 3.5,
      magicResist: 2.6,
    },
    passive: {
      name: 'Shadow Ambush',
      description: 'Attacking an enemy from behind or after coming out of stealth deals 35% bonus true damage.',
    },
    skills: [
      {
        id: 'zephyr_s1',
        name: 'Shadow Step',
        description: 'Instantly teleports behind target enemy or in target direction, slashing for physical damage.',
        cooldown: 6.5,
        currentCooldown: 0,
        manaCost: 45,
        range: 350,
        targetType: 'dash',
        damageType: 'physical',
        baseDamage: 190,
        damagePerLevel: 45,
        scalingAD: 0.9,
        scalingAP: 0,
        level: 1,
        maxLevel: 4,
        icon: '🗡️',
        color: '#a855f7',
      },
      {
        id: 'zephyr_s2',
        name: 'Phantom Shurikens',
        description: 'Hurls 3 shadow blades forward in a fan, dealing physical damage and slowing targets hit by 30%.',
        cooldown: 7.5,
        currentCooldown: 0,
        manaCost: 55,
        range: 380,
        targetType: 'cone',
        damageType: 'physical',
        baseDamage: 170,
        damagePerLevel: 40,
        scalingAD: 0.75,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '⭐',
        color: '#7e22ce',
      },
      {
        id: 'zephyr_s3',
        name: 'Smoke Shroud',
        description: 'Enters stealth and gains 40% movement speed for 3s. Attacking breaks stealth with guaranteed critical hit.',
        cooldown: 12,
        currentCooldown: 0,
        manaCost: 60,
        range: 0,
        targetType: 'self',
        damageType: 'physical',
        baseDamage: 0,
        damagePerLevel: 0,
        scalingAD: 0,
        scalingAP: 0,
        level: 0,
        maxLevel: 4,
        icon: '🌫️',
        color: '#c084fc',
      },
      {
        id: 'zephyr_ult',
        name: 'Death Mark',
        description: 'Marks target enemy champion and strikes them 4 times in rapid succession, executing low HP enemies.',
        cooldown: 30,
        currentCooldown: 0,
        manaCost: 95,
        range: 360,
        targetType: 'target_unit',
        damageType: 'physical',
        baseDamage: 520,
        damagePerLevel: 140,
        scalingAD: 1.45,
        scalingAP: 0,
        level: 0,
        maxLevel: 3,
        icon: '☠️',
        color: '#581c87',
      },
    ],
  },

  lumina: {
    id: 'lumina',
    name: 'Lumina',
    title: 'The Celestial Star',
    role: 'support',
    avatarColor: '#06b6d4',
    primaryColor: '#0891b2',
    secondaryColor: '#67e8f9',
    lore: 'A celestial priestess blessed by the astral light, Lumina shields allies and commands celestial constellations to disrupt foes.',
    baseStats: {
      hp: 2450,
      maxHp: 2450,
      mana: 550,
      maxMana: 550,
      hpRegen: 9,
      manaRegen: 6.0,
      attack: 90,
      magicPower: 40,
      armor: 34,
      magicResist: 34,
      moveSpeed: 245,
      attackSpeed: 0.9,
      attackRange: 260,
      cooldownReduction: 0.1,
      critChance: 0,
      lifesteal: 0,
    },
    growthStats: {
      hp: 165,
      mana: 30,
      attack: 5.0,
      armor: 3.8,
      magicResist: 2.8,
    },
    passive: {
      name: 'Astral Aura',
      description: 'Nearby allied heroes gain +15 movement speed and +10 HP regen per second.',
    },
    skills: [
      {
        id: 'lumina_s1',
        name: 'Healing Radiance',
        description: 'Channels a wave of radiant starlight that heals the lowest HP ally and herself.',
        cooldown: 7,
        currentCooldown: 0,
        manaCost: 65,
        range: 360,
        targetType: 'self',
        damageType: 'magical',
        baseDamage: 0,
        damagePerLevel: 0,
        scalingAD: 0,
        scalingAP: 0.8,
        level: 1,
        maxLevel: 4,
        icon: '💖',
        color: '#22d3ee',
      },
      {
        id: 'lumina_s2',
        name: 'Starlight Roots',
        description: 'Launches celestial starlight forward that roots the first 2 enemies struck for 1.4s and deals magic damage.',
        cooldown: 8.5,
        currentCooldown: 0,
        manaCost: 60,
        range: 460,
        targetType: 'skillshot_line',
        damageType: 'magical',
        baseDamage: 180,
        damagePerLevel: 45,
        scalingAD: 0,
        scalingAP: 0.65,
        level: 0,
        maxLevel: 4,
        icon: '🌟',
        color: '#06b6d4',
      },
      {
        id: 'lumina_s3',
        name: 'Prismatic Shield',
        description: 'Grants a luminous shield absorbing 240 (+60/lv) damage to target allied hero or herself for 4s.',
        cooldown: 10,
        currentCooldown: 0,
        manaCost: 70,
        range: 380,
        targetType: 'self',
        damageType: 'magical',
        baseDamage: 0,
        damagePerLevel: 0,
        scalingAD: 0,
        scalingAP: 0.7,
        level: 0,
        maxLevel: 4,
        icon: '🛡️',
        color: '#67e8f9',
      },
      {
        id: 'lumina_ult',
        name: 'Celestial Grace',
        description: 'Summons a divine cosmic aurora across the battlefield, providing a huge burst heal and 50% speed boost to all nearby allies.',
        cooldown: 42,
        currentCooldown: 0,
        manaCost: 120,
        range: 0,
        radius: 450,
        targetType: 'aoe_circle',
        damageType: 'magical',
        baseDamage: 0,
        damagePerLevel: 0,
        scalingAD: 0,
        scalingAP: 1.2,
        level: 0,
        maxLevel: 3,
        icon: '✨',
        color: '#0e7490',
      },
    ],
  },
};

export const ITEMS_CONFIG: Item[] = [
  // ATTACK
  {
    id: 'war_axe',
    name: 'War Axe',
    category: 'attack',
    cost: 1980,
    description: '+55 Physical Attack, +550 HP, +10% Cooldown Reduction.',
    icon: '🪓',
    stats: { attack: 55, maxHp: 550, cooldownReduction: 0.1 },
    passive: 'Berserk: Entering combat increases attack by up to 30 over 4s.',
  },
  {
    id: 'blade_of_despair',
    name: 'Blade of Despair',
    category: 'attack',
    cost: 3010,
    description: '+160 Physical Attack, +5% Movement Speed.',
    icon: '🗡️',
    stats: { attack: 160, moveSpeed: 15 },
    passive: 'Despair: Attacks against enemies below 50% HP deal 25% extra damage.',
  },
  {
    id: 'berserker_fury',
    name: "Berserker's Fury",
    category: 'attack',
    cost: 2250,
    description: '+65 Physical Attack, +25% Crit Chance, +40% Crit Damage.',
    icon: '⚔️',
    stats: { attack: 65, critChance: 0.25 },
    passive: 'Doom: Critical hits grant 5% Physical Attack for 2s.',
  },
  {
    id: 'demon_hunter_sword',
    name: 'Demon Hunter Blade',
    category: 'attack',
    cost: 2180,
    description: '+35 Physical Attack, +25% Attack Speed, +10% Lifesteal.',
    icon: '🗡️',
    stats: { attack: 35, attackSpeed: 0.25, lifesteal: 0.1 },
    passive: 'Devour: Basic attacks deal 9% of target current HP as bonus damage.',
  },
  {
    id: 'bloodlust_axe',
    name: 'Bloodlust Cleaver',
    category: 'attack',
    cost: 1970,
    description: '+70 Physical Attack, +10% Cooldown Reduction, +20% Spell Lifesteal.',
    icon: '🩸',
    stats: { attack: 70, cooldownReduction: 0.1, lifesteal: 0.1 },
    passive: 'Bloodthirst: Skills heal for 20% of damage dealt.',
  },
  {
    id: 'windtalker',
    name: 'Windtalker',
    category: 'attack',
    cost: 1820,
    description: '+40% Attack Speed, +20 Movement Speed, +10% Crit Chance.',
    icon: '🏹',
    stats: { attackSpeed: 0.4, moveSpeed: 20, critChance: 0.1 },
    passive: 'Typhoon: Every 5-3s, basic attack triggers chain lightning.',
  },

  // MAGIC
  {
    id: 'holy_crystal',
    name: 'Holy Crystal',
    category: 'magic',
    cost: 2180,
    description: '+100 Magic Power, +25% Magic Power scaling.',
    icon: '🔮',
    stats: { magicPower: 100 },
    passive: 'Mystery: Increases total Magic Power by 25%.',
  },
  {
    id: 'lightning_truncheon',
    name: 'Lightning Baton',
    category: 'magic',
    cost: 2250,
    description: '+75 Magic Power, +300 Mana, +10% CDR.',
    icon: '⚡',
    stats: { magicPower: 75, maxMana: 300, cooldownReduction: 0.1 },
    passive: 'Resonate: Every 6s, your next skill triggers chain lightning.',
  },
  {
    id: 'glowing_wand',
    name: 'Glowing Wand',
    category: 'magic',
    cost: 2120,
    description: '+75 Magic Power, +400 HP, +5% Movement Speed.',
    icon: '🪄',
    stats: { magicPower: 75, maxHp: 400, moveSpeed: 12 },
    passive: 'Scorch: Skills burn targets for 1.5% max HP magic damage per sec for 3s.',
  },
  {
    id: 'concentrated_energy',
    name: 'Concentrated Energy',
    category: 'magic',
    cost: 2020,
    description: '+70 Magic Power, +700 HP, +25% Magic Lifesteal.',
    icon: '🧪',
    stats: { magicPower: 70, maxHp: 700, lifesteal: 0.15 },
    passive: 'Recharge: Defeating a hero restores 10% max HP.',
  },

  // DEFENSE
  {
    id: 'blade_armor',
    name: 'Blade Armor',
    category: 'defense',
    cost: 1910,
    description: '+90 Physical Armor, +20% Crit Damage reduction.',
    icon: '🛡️',
    stats: { armor: 90 },
    passive: 'Bladed: Reflects 20% of basic attack physical damage back to attacker.',
  },
  {
    id: 'athena_shield',
    name: "Athena's Aegis",
    category: 'defense',
    cost: 2050,
    description: '+900 HP, +62 Magic Resist, +2 HP Regen.',
    icon: '🔰',
    stats: { maxHp: 900, magicResist: 62, hpRegen: 4 },
    passive: 'Shield: Takes 25% less magic damage for 5s after taking magic damage.',
  },
  {
    id: 'immortality',
    name: 'Immortality',
    category: 'defense',
    cost: 2120,
    description: '+800 HP, +30 Physical Armor.',
    icon: '👼',
    stats: { maxHp: 800, armor: 30 },
    passive: 'Resurrection: Resurrects 2.5s after death with 16% HP and 300 shield (180s CD).',
  },
  {
    id: 'dominance_ice',
    name: 'Dominance Ice',
    category: 'defense',
    cost: 2010,
    description: '+500 Mana, +70 Physical Armor, +5% Movement Speed, +10% CDR.',
    icon: '❄️',
    stats: { maxMana: 500, armor: 70, moveSpeed: 10, cooldownReduction: 0.1 },
    passive: 'Arctic Cold: Reduces nearby enemy attack speed by 30% and healing by 50%.',
  },

  // MOVEMENT
  {
    id: 'warrior_boots',
    name: 'Warrior Boots',
    category: 'movement',
    cost: 720,
    description: '+40 Movement Speed, +22 Physical Armor.',
    icon: '🥾',
    stats: { moveSpeed: 40, armor: 22 },
    passive: 'Valor: Taking physical attacks increases armor by up to 25.',
  },
  {
    id: 'tough_boots',
    name: 'Tough Boots',
    category: 'movement',
    cost: 700,
    description: '+40 Movement Speed, +22 Magic Resist, +30% Resilience.',
    icon: '👢',
    stats: { moveSpeed: 40, magicResist: 22 },
    passive: 'Fortitude: Reduces duration of crowd control by 30%.',
  },
  {
    id: 'magic_shoes',
    name: 'Magic Shoes',
    category: 'movement',
    cost: 710,
    description: '+40 Movement Speed, +10% Cooldown Reduction.',
    icon: '👟',
    stats: { moveSpeed: 40, cooldownReduction: 0.1 },
    passive: 'Swiftness: Reduces skill cooldowns.',
  },

  // JUNGLE
  {
    id: 'hunter_blade',
    name: "Hunter's Machete",
    category: 'jungle',
    cost: 650,
    description: '+20% damage to jungle monsters, +15% extra XP from monsters.',
    icon: '🗡️',
    stats: { attack: 15, moveSpeed: 10 },
    passive: 'Hunter: Restores 50 HP and 25 Mana upon defeating jungle creeps.',
  },
];
